name: 'Deja View - Similar Issues Finder'
description: 'Automatically comment on new issues with similar existing issues using semantic search'
author: 'Your Name'
branding:
  icon: 'search'
  color: 'blue'

inputs:
  chroma-api-key:
    description: 'Chroma Cloud API key'
    required: true
  chroma-tenant:
    description: 'Chroma Cloud tenant ID'
    required: true
  chroma-database:
    description: 'Chroma Cloud database name'
    required: false
    default: 'default-database'
  github-token:
    description: 'GitHub token for API access'
    required: true
    default: ${{ github.token }}
  max-issues:
    description: 'Maximum number of issues to index'
    required: false
    default: '200'
  similarity-threshold:
    description: 'Minimum similarity score to show (0.0-1.0)'
    required: false
    default: '0.7'
  max-similar-issues:
    description: 'Maximum number of similar issues to show in comment'
    required: false
    default: '5'
  index-on-run:
    description: 'Whether to re-index the repository on each run'
    required: false
    default: 'true'
  include-discussions:
    description: 'Include discussions when indexing and searching'
    required: false
    default: 'false'
  comment-template:
    description: 'Custom comment template (use {issues_table} placeholder)'
    required: false
    default: |
      ## ðŸ” Similar Issues Found
      
      I found these similar issues that might be related:
      
      {issues_table}
      
      > This comment was automatically generated by [Deja View](https://github.com/bdougie/deja-view) using semantic similarity search.

outputs:
  similar-issues-found:
    description: 'Number of similar issues found'
  commented:
    description: 'Whether a comment was posted'

runs:
  using: 'docker'
  image: 'Dockerfile'
  env:
    CHROMA_API_KEY: ${{ inputs.chroma-api-key }}
    CHROMA_TENANT: ${{ inputs.chroma-tenant }}
    CHROMA_DATABASE: ${{ inputs.chroma-database }}
    GITHUB_TOKEN: ${{ inputs.github-token }}
    INPUT_MAX_ISSUES: ${{ inputs.max-issues }}
    INPUT_SIMILARITY_THRESHOLD: ${{ inputs.similarity-threshold }}
    INPUT_MAX_SIMILAR_ISSUES: ${{ inputs.max-similar-issues }}
    INPUT_INDEX_ON_RUN: ${{ inputs.index-on-run }}
    INPUT_INCLUDE_DISCUSSIONS: ${{ inputs.include-discussions }}
    INPUT_COMMENT_TEMPLATE: ${{ inputs.comment-template }}